char *helptext[][2] = {
    {"movement", ""},
    {"========", ""},
    {"k", "move up a note"},
    {"j", "move down a note"},
    {"", ""},
    {"editing", ""},
    {"=======", ""},
    {"h/H", "lower note one semitone / octave"},
    {"l/L", "raise note one semitone / octave"},
    {"DEL", "clear a note"},
    {".", "paste last changed note"},
    /* {"x", "toggle kill"}, */
    {"", ""},
    {"song", ""},
    {"====", ""},
    {"-/_", "decrease tempo by one / ten"},
    {"=/+", "increase tempo by one / ten"},
    {"", ""},
    {"program", ""},
    {"=======", ""},
    {"?", "show help"},
    {"^C^C", "quit"},
    {(void *) 0, (void *) 0},
};
